#!/usr/bin/env sh

curl -I -X POST https://cpanel-box5127.bluehost.com/cpsess0001371716/execute/VersionControl/update
curl -I -X POST https://cpanel-box5127.bluehost.com/cpsess0001371716/execute/VersionControlDeployment/create